### ISSUE TITLE
binding site mapping (real number - custom feature)

### ISSUE THREAD

**Issue by jure-praznikar** [i2bc/SURFMAP#12]
Why is the "binding site" option limited to discrete values? It would make more sense if this option simply took the B values (real number - custom feature) and projected them in 2D?
Let us say I have entered some features in the B-factor column (no discrete values). How can I project my custom features into the 2D map (without creating the matrix file on my own)?

PS: I also had problems building everything whiteout docker. Everything works, just not "electrostatics". It crashes at step 2 (self.async, syntax error), and in the .bashrc the environment (export APBS='path to apbs') should be defined, otherwise, the user gets the error message that the environment APBS does not exist.

**Comment by nchenche** [comment]
Dear Jure,

Apologize for the response time.

Actually, the option you are asking for already exists. You have to use the keyword `bfactor` with the `-tomap` argument :
```
surfmap -pdb foo.pdb -tomap bfactor
```

About the APBS issues, we are not responsible for the installation of the program. We are aware that it can be cumbersome to make it work with SURMAP, that is why we provided a docker image. 

Hope this helps,

Thank you for your interest in SURFMAP,

NC

**Comment by jure-praznikar** [comment]
Thank you. I was confused about the "bfactor" option. So the "bfactor" and "nosmooth" options lead to a very similar result (same interpretation) as if just the "binding_sites" option is applied. (The bfactor column contains zeros and ones for the binding site)
