### ISSUE TITLE
[Bug]: Could not use the docker in labs server computer. 

### ISSUE THREAD

**Issue by Biosuperkitty** [i2bc/SURFMAP#17]
### Operating System

Unix (e.g., Ubuntu 20.04)

### Version

2.0.0

### Python Virtual Environment

Not using a virtual environment

### Execution Environment

Encapsulated environment from the SURFMAP Docker image

### Bug Description

Thank you for taking the time to read my message.

I am new to the field of bioinformatics and recently came across a valuable software called Surfmap on GitHub. I believe that Surfmap is an excellent tool for protein structure research.

However, when I tried using Surfmap on our lab's server computer with the following command: "surfmap -pdb foo.pdb -tomap stickiness --docker", I encountered an error:

Traceback (most recent call last):
File "/surfmap/.env/bin/surfmap", line 33, in <module>
sys.exit(load_entry_point('surfmap', 'console_scripts', 'surfmap')())
File "/surfmap/surfmap/bin/surfmap.py", line 55, in main
set_root_logger(outpath=params.outdir, level=params.verbose)
File "/surfmap/surfmap/lib/logs.py", line 90, in set_root_logger
file_handler = logging.FileHandler(filename=log_filename, mode="w+")
File "/usr/lib/python3.10/logging/init.py", line 1169, in init
StreamHandler.init(self, self._open())
File "/usr/lib/python3.10/logging/init.py", line 1201, in _open
return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/home/surfmap/output/surfmap.log'

I am unsure if this issue is caused by a bug in our system or in Docker. Is there anything I can do to resolve this problem? Your assistance would be greatly appreciated.

Thank you once again for your time.

### Steps to Reproduce

conda activate surfmap
surfmap -pdb foo.pdb -tomap stickiness --docker

### Relevant Log Output

```shell
Traceback (most recent call last):
File "/surfmap/.env/bin/surfmap", line 33, in <module>
sys.exit(load_entry_point('surfmap', 'console_scripts', 'surfmap')())
File "/surfmap/surfmap/bin/surfmap.py", line 55, in main
set_root_logger(outpath=params.outdir, level=params.verbose)
File "/surfmap/surfmap/lib/logs.py", line 90, in set_root_logger
file_handler = logging.FileHandler(filename=log_filename, mode="w+")
File "/usr/lib/python3.10/logging/init.py", line 1169, in init
StreamHandler.init(self, self._open())
File "/usr/lib/python3.10/logging/init.py", line 1201, in _open
return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/home/surfmap/output/surfmap.log'
```

### Confirmation

- [X] I confirm I have searched for duplicates and reviewed the relevant documentation.

**Comment by nchenche** [comment]
Hello,

First of all, thank you for your interest in SURFMAP.

It seems like your are not allowed to create '/home/surfmap/output/surfmap.log' and right now i don't understand why...

Do you have the write permission on your local environment, id est at the location you are when you enter the command ` surfmap -pdb foo.pdb -tomap stickiness --docker`? To check it, please send me the result of `ls -l` from the location you were trying to run surfmap.

Also, are you sure of the surfmap docker version you are using? Could you please verify it with the command `surfmap -v`?

Thanks

**Comment by Biosuperkitty** [comment]
Thank you for your kind reply. Here is the result of "ls -l" from the location where I attempted to run surfmap:

drwxrwxr-x 5 Ian Ian 4096 Dec 30 16:59 result
drwxrwxr-x 6 Ian Ian 4096 Dec 30 16:56 sample
The result of "surfmap -v" is:

SURFMAP: Projection of protein surface features on 2D map
Copyright (C) 2021 H. Schweke
Version: 2.0.0
In addition, since I could not use docker images, I tried to install the software as you mentioned. I was able to successfully use "surfmap -pdb foo.pdb -tomap stickiness" to produce 2D figures without docker, and the results look good.

However, my primary aim was to use the "electrostatics" mode, which may be more related to DNA and protein interaction. I installed the APBS software from "https://apbs.readthedocs.io/en/latest/releases.html#apbs-3-4-1-apr-2022". After installation, I typed "apbs" and it worked well. But when I used "surfmap -pdb foo.pdb -tomap electrostatics", it presented an error:

SURFACE MAPPING OF THE ELECTROSTATICS PROPERTY
Step 1: computing a shell around the protein surface
Step 2: computing electrostatics potential
Traceback (most recent call last):
File "/home/xielong/miniconda3/envs/surfmap/bin/surfmap", line 8, in <module>
sys.exit(main())
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/site-packages/surfmap/bin/surfmap.py", line 63, in main
surfmap_local(params=params)
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/site-packages/surfmap/bin/surfmap.py", line 18, in surfmap_local
surfmap_from_pdb(params=params)
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/site-packages/surfmap/lib/core.py", line 169, in surfmap_from_pdb
shell = run_compute_electrostatics(pdb_filename=params.pdbarg, csv_filename=csv_coords, force_field=params.force_field, pqr_filename=params.pqr, out_dir=outdir_elec)
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/site-packages/surfmap/tools/compute_electrostatics.py", line 93, in run
PATH_APBS = Path(os.getenv("APBS"))
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/pathlib.py", line 1027, in new
self = cls._from_parts(args, init=False)
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/pathlib.py", line 674, in _from_parts
drv, root, parts = self._parse_args(args)
File "/home/xielong/miniconda3/envs/surfmap/lib/python3.7/pathlib.py", line 658, in _parse_args
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

It seems like surfmap could not find "APBS", and I'm not sure why.

Is there anything I can do to resolve this problem? Your assistance would be greatly appreciated. Sorry for bringing you so many problems. Thank you again for your time.

**Comment by nchenche** [comment]
Dear Xielong (i guess),

First be aware that i moved the second part of your message and created a new issue from it as it does not directly relate to your first issue. Indeed, as a managing perspective, it is not practical for anyone to mix up multiple unrelated issues. I have answered it [here](https://github.com/i2bc/SURFMAP/issues/17).

Next, I see that username of the surfmap user (xielong) and username of the owner of the directory you are expecting results (Ian) do not match:

```
drwxrwxr-x 5 Ian Ian 4096 Dec 30 16:59 result
drwxrwxr-x 6 Ian Ian 4096 Dec 30 16:56 sample
```

```
# output taken from https://github.com/i2bc/SURFMAP/issues/18
SURFACE MAPPING OF THE ELECTROSTATICS PROPERTY
Step 1: computing a shell around the protein surface
Step 2: computing electrostatics potential
Traceback (most recent call last):
File "/home/xielong/miniconda3/envs/surfmap/bin/surfmap", line 8
...
```
It could explain your issue since, if it is the case, xielong user running surfmap will not be allowed to write on Ian directories.

Please let me know if I got wrong and misinterpret it.

**Comment by Biosuperkitty** [comment]
Thank you for your kind response. I relocated the file to my personal folder, and do "chmod 777" to my working folder, and now it is functioning perfectly. The issue has been resolved, and I would like to express my sincere gratitude for your assistance.

Haha. (But I found docker is much slower than primary using)
let's move to the next issue.
