### ISSUE TITLE
[Question]: Best way to handle Inf when comparing vectors?

### ISSUE THREAD

**Issue by EvanKomp** [i2bc/SURFMAP#20]
### Feature Title

Best way to handle Inf when comparing vectors?

### Feature Summary

Comparing smoothed matrices is hindered by Inf, not sure how best to handle them. Thanks for your tool!!!

### Motivation and Context

I have run SURFMAP for a number of homologs, and have smoothed matrices for each. 

I want to compare the matrices over different groups, eg. take the mean of a couple etc.

I am not sure what to do with Inf positions, maybe from a lack of understanding of what they actually are. Are these positions on the projection sphere without any nearby residuess to map?

Regardless, I am thinking and converting all Inf to Nan and doing Nan-ignoring operations over the vectors. Any wisdom is appreciated.

### Duplicate Check

- [X] I have searched the existing feature requests and did not find a duplicate.

**Comment by EvanKomp** [comment]
It seems as if any index that is Inf in one is Inf in all - though confirmation would be lovely

![image](https://github.com/i2bc/SURFMAP/assets/56170658/10cb1c9d-85d8-4da2-a11a-37c3141fdfad)

**Comment by nchenche** [comment]
Dear EvanKomp,

'Inf' values refer to cells in the border of the projection, _id est_ cells that do not correspond to any protein residue(s). So  indeed "Inf" value should be the same between all your maps/matrices.

To answer your question clearly: you should not consider "Inf" values when quantitatively operating on SURFMAP matrices.

Sorry for the delay, hope this will help.

Bests
