### ISSUE TITLE
link for SURFMAP

### ISSUE THREAD

**Issue by HugoSchweke** [i2bc/SURFMAP#3]
Hi Nicolas,

Just one little thing: when putting a link to SURFMAP (we put one at the end of the paper), should we use the following address:
https://github.com/i2bc/SURFMAP

In the documentation, the link is:
https://github.com/i2bc/SURFMAP#Run-SURFMAP-through-its-pre-built-docker-image

that leads to the same page. Is it the final address for SURFMAP? If yes I guess best is to put the first address in the paper, right?

**Comment by nchenche** [comment]
Hi Hugo,

Yes indeed this is the first link that must be used. The second refers to a wrong location that I will fix now!

Thanks
